Repository wantedPreOnboarding/19_08th_fileshare, pull requests merged in 2022-02, with the labels that each got.

#8 [송현] Add - 라우터 적용
  package.json
  public/manifest.json
  src/App.tsx
  src/index.tsx
  src/pages/DetailPage/index.tsx
  src/styles/theme.ts
  yarn.lock
Labels: setting

#13 [다빈] Add - 파일 사이즈 출력, 유효 기간 계산, 리스트 구현
  src/components/data.json
  src/hooks/useInterval.tsx
  src/pages/LinkPage/TableBody.tsx
  src/pages/LinkPage/index.style.ts
  src/pages/LinkPage/index.tsx
  src/types/data.type.ts
  src/types/props.ts
  src/utils/commaNumber.test.ts
  src/utils/commaNumber.ts
  src/utils/formatFileSize.test.ts
  src/utils/formatFileSize.ts
  src/utils/inputClipboard.ts
  src/utils/printFileSize.ts
  src/utils/printRemainTime.ts
Labels: enhancement

#15 [다빈] Add - 클립보드 복사 시 Alert 기능
  src/pages/LinkPage/TableBody.tsx
  src/pages/LinkPage/index.style.ts
  src/utils/inputClipboard.ts
Labels: enhancement

#19 [다빈] Add - 리스트에서 유효기간에 따라 URL 표시와 클립보드 동작 설정
  src/pages/LinkPage/TableBody.tsx
  src/utils/printFilteredUrl.ts
Labels: enhancement

#20 [영종] Add - 삭제 액션, File(전체,단일) 조회 selector
  package.json
  src/App.tsx
  src/redux/sagas/fetchFileList.ts
  src/redux/selectors/fileList.ts
  src/redux/selectors/index.ts
  src/redux/slices/fileList.ts
  src/redux/utils/arrayToObject.ts
  yarn.lock
Labels: enhancement

#22 [영종] Fix - loadFileList action에만 fetchFileList saga가 실행되도록 설정
  src/App.tsx
  src/redux/sagas/fetchFileList.ts
  src/redux/sagas/root.ts
Labels: enhancement

#23 Add 데이터 리덕스 연결 및 file예외처리
  src/pages/DetailPage/index.tsx
  src/utils/formatDate.ts
Labels: enhancement

#24 [다빈] Add - Link Page에 데이터 리덕스 연결, 기간 만료 시 link 스타일 변경
  src/pages/LinkPage/TableBody.tsx
  src/pages/LinkPage/index.style.ts
  src/pages/LinkPage/index.tsx
  src/utils/index.ts
  src/utils/inputClipboard.ts
Labels: enhancement, style
